pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    tools {
        nodejs 'node16'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/Speed013/uber-clone.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-scanner') {
                    sh '''
                      $SCANNER_HOME/bin/sonar-scanner \
                      -Dsonar.projectName=Application_deployment \
                      -Dsonar.projectKey=Application_deployment
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                waitForQualityGate abortPipeline: false, credentialsId: 'sonartoken'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('OWASP FS SCAN') {
            steps {
                dependencyCheck(
                    additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit',
                    odcInstallation: 'DP-Check'
                )

                dependencyCheckPublisher(
                    pattern: '**/dependency-check-report.xml'
                )
            }
        }

        stage('TRIVY FS SCAN') {
            steps {
                sh '''
                  docker run --rm \
                  -v $WORKSPACE:/workspace \
                  aquasec/trivy:latest fs /workspace > trivyfs.json
                '''
            }
        }

        stage('Docker Build & Push') {
            steps {
                withDockerRegistry(credentialsId: 'dockerpass', toolName: 'docker') {
                    sh '''
                      docker system prune -af --volumes
                      docker build -t uber .
                      docker tag uber speed013/uber:latest
                      docker push speed013/uber:latest
                    '''
                }
            }
        }

        stage('TRIVY IMAGE SCAN') {
            steps {
                sh '''
                  docker run --rm \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  aquasec/trivy:latest image speed013/uber:latest > trivyimage.json
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                  aws eks update-kubeconfig --region us-east-1 --name EKS_CLOUD
                  kubectl apply -f K8S/deployment.yml
                  kubectl apply -f K8S/service.yml
                '''
            }
        }
    }
}
